In [1]:
import pandas as pd

In [2]:
pisa_historic = pd.read_csv("OECD PISA data.csv")

pisa_historic = pisa_historic[pisa_historic['SUBJECT'] == 'TOT']

pisa_historic = pisa_historic.groupby(['LOCATION', 'TIME'])['Value'].mean().reset_index()

pisa_historic = pisa_historic.rename(columns={
    'LOCATION': 'geo', 
    'TIME': 'year', 
    'Value': 'pisa_score'
})

In [3]:
# Dicionário de conversão (ISO Alpha-2 para ISO Alpha-3)
iso2_to_iso3 = {
    'SG': 'SGP', 'CN': 'CHN', 'JP': 'JPN', 'TW': 'TWN', 'KR': 'KOR', 'HK': 'HKG',
    'EE': 'EST', 'CA': 'CAN', 'IE': 'IRL', 'CH': 'CHE', 'AU': 'AUS', 'FI': 'FIN',
    'NZ': 'NZL', 'GB': 'GBR', 'PL': 'POL', 'CZ': 'CZE', 'DK': 'DNK', 'US': 'USA',
    'SE': 'SWE', 'BE': 'BEL', 'AT': 'AUT', 'SI': 'SVN', 'LV': 'LVA', 'DE': 'DEU',
    'NL': 'NLD', 'FR': 'FRA', 'PT': 'PRT', 'ES': 'ESP', 'HU': 'HUN', 'LT': 'LTU',
    'IT': 'ITA', 'NO': 'NOR', 'HR': 'HRV', 'VN': 'VNM', 'IL': 'ISR', 'TR': 'TUR',
    'MT': 'MLT', 'SK': 'SVK', 'IS': 'ISL', 'RS': 'SRB', 'UA': 'UKR', 'BN': 'BRN',
    'GR': 'GRC', 'CL': 'CHL', 'RO': 'ROU', 'AE': 'ARE', 'UY': 'URY', 'QA': 'QAT',
    'BG': 'BGR', 'MD': 'MDA', 'KZ': 'KAZ', 'MX': 'MEX', 'MN': 'MNG', 'ME': 'MNE',
    'MY': 'MYS', 'CR': 'CRI', 'CY': 'CYP', 'PE': 'PER', 'CO': 'COL', 'BR': 'BRA',
    'JM': 'JAM', 'AR': 'ARG', 'TH': 'THA', 'SA': 'SAU', 'GE': 'GEO', 'AZ': 'AZE',
    'PA': 'PAN', 'MK': 'MKD', 'ID': 'IDN', 'AL': 'ALB', 'GT': 'GTM', 'PS': 'PSE',
    'SV': 'SLV', 'PY': 'PRY', 'JO': 'JOR', 'MA': 'MAR', 'PH': 'PHL', 'UZ': 'UZB',
    'DO': 'DOM', 'KH': 'KHM'
}

In [4]:
pisa_2022 = pd.read_csv("pisa-scores-by-country-2026.csv")

pisa_2022['geo'] = pisa_2022['flagCode'].map(iso2_to_iso3)

pisa_2022['year'] = 2022

cols_notas = ['PISAScoresMathScore_2022', 'PISAScoresScienceScore_2022', 'PISAScoresReadingScore_2022']
pisa_2022['pisa_score'] = pisa_2022[cols_notas].mean(axis=1)

pisa_2022_clean = pisa_2022[['geo', 'year', 'pisa_score']].dropna(subset=['geo'])

In [5]:
pisa_master = pd.concat([pisa_historic, pisa_2022_clean], ignore_index=True)

pisa_master = pisa_master.sort_values(by=['geo', 'year'])

pisa_master.to_csv('pisa_master_dataset.csv', index=False)

pisa_master.head()

     geo  year  pisa_score
336  ALB  2022  367.333333
312  ARE  2022  426.666667
328  ARG  2022  395.000000
0    AUS  2000  528.000000
1    AUS  2003  524.500000

In [6]:
pisa_master['geo'].unique()

array(['ALB', 'ARE', 'ARG', 'AUS', 'AUT', 'AZE', 'BEL', 'BGR', 'BRA',
       'BRN', 'CAN', 'CHE', 'CHL', 'CHN', 'COL', 'CRI', 'CYP', 'CZE',
       'DEU', 'DNK', 'DOM', 'ESP', 'EST', 'FIN', 'FRA', 'GBR', 'GEO',
       'GRC', 'GTM', 'HKG', 'HRV', 'HUN', 'IDN', 'IRL', 'ISL', 'ISR',
       'ITA', 'JAM', 'JOR', 'JPN', 'KAZ', 'KHM', 'KOR', 'LTU', 'LUX',
       'LVA', 'MAC', 'MAR', 'MDA', 'MEX', 'MKD', 'MLT', 'MNE', 'MNG',
       'MYS', 'NLD', 'NOR', 'NZL', 'OAVG', 'PAN', 'PER', 'PHL', 'POL',
       'PRT', 'PRY', 'PSE', 'QAT', 'ROU', 'RUS', 'SAU', 'SGP', 'SLV',
       'SRB', 'SVK', 'SVN', 'SWE', 'THA', 'TUR', 'TWN', 'UKR', 'URY',
       'USA', 'UZB', 'VNM'], dtype=object)

In [7]:
pisa_master.sample(10)

      geo  year  pisa_score
345   DOM  2022  350.000000
79    EST  2009  513.666667
291   NLD  2022  480.000000
323   CYP  2022  403.333333
130   IRL  2018  504.666667
87    FIN  2012  529.333333
51    CZE  2003  502.500000
193   NOR  2000  505.000000
123   IDN  2018  382.000000
207  OAVG  2006  496.000000